branch-defaults:
  main:
    environment: sushi-invoice-app
    group_suffix: null

global:
  application_name: sushi-invoice-app
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application 